### ISSUE TITLE
normalizing IN queries should be a little nicer

### ISSUE THREAD

**Issue by christineyen** [honeycombio/mysqltools#3]
not sure if this belongs in honeycombio/mysqltools or honeycombio/sqlparser, but here's a failing test that would be nice to not be failing:

(added to the end of [parser_test.go](https://github.com/honeycombio/mysqltools/blob/master/query/normalizer/parser_test.go#L131)):

	{"in query",
		"SELECT colname, fooname FROM tablename WHERE id IN (1, 2, 3, 5, 8, 13) ORDER BY date",
		"select colname, fooname from tablename where id in (?) order by date",
		"select",
		[]string{"tablename"},
		[]string{},
	},

**Comment by maplebed** [comment]
fixed in PR #6

**Comment by JamieDanielson** [comment]
Closing issue as per above-mentioned fix already merged in.
