### ISSUE TITLE
Table and column names with quotes are removed from normalized query

### ISSUE THREAD

**Issue by jasonarewhy** [honeycombio/mysqltools#7]
While testing the `rdslogs` tool, I noticed our normalized queries looked so bare as to be not useful at all:

```
update ? set ? = ?, ? = ?, ? = ? where ?.? = ?
select ?.* from ? where ?.? = ? order by report_runs.created_at desc limit ? offset ?
insert into ? (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) values (?, ?, ?, ?, ?, ?, ?, ?, ???????????, ?, ?) returning ?
select ?.* from ? where ?.? in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```

After taking a look at the underlying normalizer tests, it appears these should look closer to something like `update tablename set colname = ?, colname2 = ?, colname3 = ? where tablename.colname = ?`, where table and column names are kept intact, only literal values being removed.

I've narrowed down the case to single or double quotes around the table/column names. Using the [tester](https://github.com/honeycombio/mysqltools/tree/master/tester), I added some output to see before and after:

**double quotes**
```sql
input:
SELECT COUNT(*) FROM "tablename" WHERE (tablename.colname = 12345)

normalized: 
select count(*) from ? where (tablename.colname = ?)
```

**single quotes**
```sql
input: 
SELECT COUNT(*) FROM 'tablename' WHERE (tablename.colname = 12345)

normalized: 
select count(*) from ? where (tablename.colname = ?)
```

**no quotes**
```sql
input: 
SELECT COUNT(*) FROM tablename WHERE (tablename.colname = 12345)

normalized:
select count(*) from tablename where (tablename.colname = ?)
```

**backticks**
```sql
input: 
SELECT COUNT(*) FROM `tablename` WHERE (tablename.colname = 12345)

normalized:
select count(*) from `tablename` where (tablename.colname = ?)
```

Without becoming deeply familiar with the code, I'm not sure whether fixing this behavior is feasible or would require a major re-write, but in Postgres, it is valid to quote table and column names in order to make them case-sensitive. Until we can get more useful normalized queries, sending our query logs to honeycomb has pretty limited usefulness for us. Thanks for any help! ❤️ 🐝

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
